# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print("NumPy version:", np.__version__)
np.show_config()


NumPy version: 2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/vigus/anaconda3/Library/include
    lib directory: C:/Users/vigus/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/vigus/anaconda3/Library/include
    lib directory: C:/Users/vigus/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cytho

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
a = np.random.random((2, 3, 5))

a = np.random.rand(2, 3, 5)

rng = np.random.default_rng()
a = rng.random((2, 3, 5))



### 4. Print a.


In [6]:
print(a)

[[[0.17566445 0.24166438 0.77730946 0.08444066 0.21518022]
  [0.995746   0.53363182 0.69918248 0.55060964 0.47073651]
  [0.53118966 0.43927275 0.86256446 0.84150703 0.3251277 ]]

 [[0.22683176 0.36634237 0.25422497 0.42874773 0.84510216]
  [0.22573279 0.09055222 0.75289134 0.30986046 0.62983087]
  [0.96299079 0.43984022 0.55120239 0.51468538 0.54230968]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [7]:
b = np.ones((5, 2, 3))



### 6. Print b.


In [8]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [10]:
print("Size of a:", a.size)
print("Size of b:", b.size)

print("Same Size?", a.size == b.size)

Size of a: 30
Size of b: 30
Same Size? True



### 8. Are you able to add a and b? Why or why not?


In [12]:
a.shape = (2, 3, 5)
b.shape = (5, 2, 3)

a + b

# ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
# The value error above is expected because the shapes are not compatible for broadcasting. 
# NumPy compares the shapes from right to left, and in this case,
# the dimensions 3 and 2 are not compatible since   
# the broadcasting rules require that the dimensions are either equal or one of them is 1.


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [14]:
c = np.transpose(b, (1, 2, 0))

print('Shape a', a.shape)
print('Shape b', b.shape)
print('Shape c', c.shape)

c.shape == (2, 3 ,5)



Shape a (2, 3, 5)
Shape b (5, 2, 3)
Shape c (2, 3, 5)


True


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [16]:
d = a + c
print('shape d', d.shape)

# a.shape and c.shape are compatible for broadcasting because:
# The all dimensions are equal.
# since the shapes are identical, NumPy can add them element by element



shape d (2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print("Array a:\n", a)
print("\nArray d:\n", d)

# a is an array with values between 0 and 1
# c (transposed b) is an array of ones with the same shape as a
# Therefore, when we add a and c, each element in a is increased by 1
# resulting in an array d with values between 1 and 2 or d=a+1



Array a:
 [[[0.17566445 0.24166438 0.77730946 0.08444066 0.21518022]
  [0.995746   0.53363182 0.69918248 0.55060964 0.47073651]
  [0.53118966 0.43927275 0.86256446 0.84150703 0.3251277 ]]

 [[0.22683176 0.36634237 0.25422497 0.42874773 0.84510216]
  [0.22573279 0.09055222 0.75289134 0.30986046 0.62983087]
  [0.96299079 0.43984022 0.55120239 0.51468538 0.54230968]]]

Array d:
 [[[1.17566445 1.24166438 1.77730946 1.08444066 1.21518022]
  [1.995746   1.53363182 1.69918248 1.55060964 1.47073651]
  [1.53118966 1.43927275 1.86256446 1.84150703 1.3251277 ]]

 [[1.22683176 1.36634237 1.25422497 1.42874773 1.84510216]
  [1.22573279 1.09055222 1.75289134 1.30986046 1.62983087]
  [1.96299079 1.43984022 1.55120239 1.51468538 1.54230968]]]



### 12. Multiply a and c. Assign the result to e.


In [18]:
e = a * c
print('Shape e', e.shape)


Shape e (2, 3, 5)




### 13. Does e equal to a? Why or why not?


In [19]:
# e equals to a
# Since c is an array of ones, multiplying a by c leaves a unchanged.

print(np.array_equal(a, e))  # This will print True



True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [20]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print('Max value in d:', d_max)
print('Min value in d:', d_min)
print('Mean value in d:', d_mean)


Max value in d: 1.9957460039760746
Min value in d: 1.0844406608668198
Mean value in d: 1.4961657444005783



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [21]:
f = np.empty(d.shape)
print('Shape f', f.shape)
print('Array of f', f)


Shape f (2, 3, 5)
Array of f [[[1.17566445 1.24166438 1.77730946 1.08444066 1.21518022]
  [1.995746   1.53363182 1.69918248 1.55060964 1.47073651]
  [1.53118966 1.43927275 1.86256446 1.84150703 1.3251277 ]]

 [[1.22683176 1.36634237 1.25422497 1.42874773 1.84510216]
  [1.22573279 1.09055222 1.75289134 1.30986046 1.62983087]
  [1.96299079 1.43984022 1.55120239 1.51468538 1.54230968]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [22]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75

print(f)

[[[ 25.  25.  75.   0.  25.]
  [100.  75.  75.  75.  25.]
  [ 75.  25.  75.  75.  25.]]

 [[ 25.  25.  25.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  25.  75.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [24]:
print("Array d:\n", d)
print("\nArray f:\n", f)

# d has floating-point numbers in [1, 2).
# f has only {0, 25, 50, 75, 100}.
# Each position in f corresponds to the classification of the same position in d

Array d:
 [[[1.17566445 1.24166438 1.77730946 1.08444066 1.21518022]
  [1.995746   1.53363182 1.69918248 1.55060964 1.47073651]
  [1.53118966 1.43927275 1.86256446 1.84150703 1.3251277 ]]

 [[1.22683176 1.36634237 1.25422497 1.42874773 1.84510216]
  [1.22573279 1.09055222 1.75289134 1.30986046 1.62983087]
  [1.96299079 1.43984022 1.55120239 1.51468538 1.54230968]]]

Array f:
 [[[ 25.  25.  75.   0.  25.]
  [100.  75.  75.  75.  25.]
  [ 75.  25.  75.  75.  25.]]

 [[ 25.  25.  25.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  25.  75.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [27]:
Strings = np.empty(d.shape, dtype=object)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                Strings[i, j, k] = "A"   
            elif value == d_max:
                Strings[i, j, k] = "E"   
            elif value == d_mean:
                Strings[i, j, k] = "C"   
            elif d_min < value < d_mean:
                Strings[i, j, k] = "B"   
            elif d_mean < value < d_max:
                Strings[i, j, k] = "D" 

print(Strings)

[[['B' 'B' 'D' 'A' 'B']
  ['E' 'D' 'D' 'D' 'B']
  ['D' 'B' 'D' 'D' 'B']]

 [['B' 'B' 'B' 'B' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'B' 'D' 'D' 'D']]]
